### ISSUE TITLE
In /list Etherpad hyperlinks are broken

### ISSUE THREAD

**Issue by pkleanthous-zz** [esripdx/ep_padlist#9]
Hello,

when I'm in myserver.com/list 

the hyperlinks on Etherpads are wrong

Example:
I have the etherpad "Test-etherpad"

As it is the hyperlink points to myserver.com/Test-etherpad

The correct hyperlink should be  myserver.com**/p/**Test-etherpad

The /p/ is missing.

I would like to help and fix this. Can your guide me ?

**Comment by pht31337** [comment]
https://github.com/Piotr-Pht-Jasiek/ep_padlist/tree/patch-1

fixed
